apiVersion: v1
kind: Pod
metadata:
  name: apollo-optimizer
  labels:
    app: cfgrec
spec:
  
  containers:
  - name: test-container
    image: cfgrec:latest
    imagePullPolicy: Never
    volumeMounts:
    - name: cfgmap  
      mountPath: /usr/bin
    - name: local
      mountPath: /usr/local
    - name: run
      mountPath: /var/run
    - name: kube
      mountPath: /root/.kube
  volumes:
  - name: cfgmap
    hostPath:
      path: /usr/bin
  - name: local
    hostPath:
      path: /usr/local
  - name: run
    hostPath:
      path: /var/run
  - name: kube
    hostPath:
      path: /root/.kube
