apiVersion: v1
kind: Pod
metadata:
  name: test2
  labels:
    app: tmp
spec:
  
  containers:
  - name: test-container
    image: tmp:latest
    imagePullPolicy: Never
    volumeMounts:
    - name: ssl-certs
      mountPath: /usr/bin
  volumes:
  - name: ssl-certs
    hostPath:
      path: /usr/bin
